server:
  port: 8080

spring:
  config:
    import: optional:classpath:env.properties
  security:
    oauth2:
      client:
        registration:
          eve:
            client-name: eve
            client-id: ${eve.oauth2.client.id} #  https://developers.eveonline.com/
            client-secret: ${eve.oauth2.client.secret} #  https://developers.eveonline.com/
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/eve # https://developers.eveonline.com/
          #            scope: publicData
        provider:
          eve:
            authorization-uri: https://login.eveonline.com/v2/oauth/authorize
            token-uri: https://login.eveonline.com/v2/oauth/token
            user-info-uri: https://login.eveonline.com/oauth/verify
            user-name-attribute: CharacterName
      resourceserver:
        jwt:
          jwk-set-uri: https://login.eveonline.com/oauth/jwks
          issuer-uri: https://login.eveonline.com

